// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0qZ4Xk61fKBqUzXkM0o4Ba7jFm9pvqmA',
    appId: '1:709661603087:web:9007bbbce7dc471b973a7a',
    messagingSenderId: '709661603087',
    projectId: 'contactless-order-a07c0',
    authDomain: 'contactless-order-a07c0.firebaseapp.com',
    storageBucket: 'contactless-order-a07c0.firebasestorage.app',
    measurementId: 'G-6SLV6GTSF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDajpHCq54BR2KWUY3eM-CdFIMu79P0brg',
    appId: '1:709661603087:android:0d4d755fb457269c973a7a',
    messagingSenderId: '709661603087',
    projectId: 'contactless-order-a07c0',
    storageBucket: 'contactless-order-a07c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIGsE0724HnSbhEylRiSH4yhZ14UhYos',
    appId: '1:709661603087:ios:05a2f97830b5c36a973a7a',
    messagingSenderId: '709661603087',
    projectId: 'contactless-order-a07c0',
    storageBucket: 'contactless-order-a07c0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantOrderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIGsE0724HnSbhEylRiSH4yhZ14UhYos',
    appId: '1:709661603087:ios:05a2f97830b5c36a973a7a',
    messagingSenderId: '709661603087',
    projectId: 'contactless-order-a07c0',
    storageBucket: 'contactless-order-a07c0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantOrderingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0qZ4Xk61fKBqUzXkM0o4Ba7jFm9pvqmA',
    appId: '1:709661603087:web:1cf04b70f9163e51973a7a',
    messagingSenderId: '709661603087',
    projectId: 'contactless-order-a07c0',
    authDomain: 'contactless-order-a07c0.firebaseapp.com',
    storageBucket: 'contactless-order-a07c0.firebasestorage.app',
    measurementId: 'G-BXQWC73S76',
  );
}
